// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace bstrkr.core {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("bstrkr.core.AppResources_ru", typeof(AppResources_ru).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string about_view_title {
            get {
                return ResourceManager.GetString("about_view_title", resourceCulture);
            }
        }
        
        public static string map_view_title {
            get {
                return ResourceManager.GetString("map_view_title", resourceCulture);
            }
        }
        
        public static string routes_view_title {
            get {
                return ResourceManager.GetString("routes_view_title", resourceCulture);
            }
        }
        
        public static string route_stops_view_title {
            get {
                return ResourceManager.GetString("route_stops_view_title", resourceCulture);
            }
        }
        
        public static string close_route_stops_view_title {
            get {
                return ResourceManager.GetString("close_route_stops_view_title", resourceCulture);
            }
        }
        
        public static string all_route_stops_view_title {
            get {
                return ResourceManager.GetString("all_route_stops_view_title", resourceCulture);
            }
        }
        
        public static string preferences_view_title {
            get {
                return ResourceManager.GetString("preferences_view_title", resourceCulture);
            }
        }
        
        public static string route_stop_view_title_format {
            get {
                return ResourceManager.GetString("route_stop_view_title_format", resourceCulture);
            }
        }
        
        public static string licenses_view_title {
            get {
                return ResourceManager.GetString("licenses_view_title", resourceCulture);
            }
        }
        
        public static string unknown_location_dialog_title {
            get {
                return ResourceManager.GetString("unknown_location_dialog_title", resourceCulture);
            }
        }
        
        public static string locations_dialog_title {
            get {
                return ResourceManager.GetString("locations_dialog_title", resourceCulture);
            }
        }
        
        public static string stops_dialog_title {
            get {
                return ResourceManager.GetString("stops_dialog_title", resourceCulture);
            }
        }
        
        public static string routes_dialog_title {
            get {
                return ResourceManager.GetString("routes_dialog_title", resourceCulture);
            }
        }
        
        public static string unknown_location_dialog_text {
            get {
                return ResourceManager.GetString("unknown_location_dialog_text", resourceCulture);
            }
        }
        
        public static string unknown_location_no_data {
            get {
                return ResourceManager.GetString("unknown_location_no_data", resourceCulture);
            }
        }
        
        public static string troll_vehicle_type_title {
            get {
                return ResourceManager.GetString("troll_vehicle_type_title", resourceCulture);
            }
        }
        
        public static string bus_vehicle_type_title {
            get {
                return ResourceManager.GetString("bus_vehicle_type_title", resourceCulture);
            }
        }
        
        public static string minibus_vehicle_type_title {
            get {
                return ResourceManager.GetString("minibus_vehicle_type_title", resourceCulture);
            }
        }
        
        public static string tramway_vehicle_type_title {
            get {
                return ResourceManager.GetString("tramway_vehicle_type_title", resourceCulture);
            }
        }
        
        public static string troll_route_title_format {
            get {
                return ResourceManager.GetString("troll_route_title_format", resourceCulture);
            }
        }
        
        public static string bus_route_title_format {
            get {
                return ResourceManager.GetString("bus_route_title_format", resourceCulture);
            }
        }
        
        public static string minibus_route_title_format {
            get {
                return ResourceManager.GetString("minibus_route_title_format", resourceCulture);
            }
        }
        
        public static string tramway_route_title_format {
            get {
                return ResourceManager.GetString("tramway_route_title_format", resourceCulture);
            }
        }
        
        public static string no_thanks {
            get {
                return ResourceManager.GetString("no_thanks", resourceCulture);
            }
        }
        
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        public static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        public static string route_vehicle_arrives_st_format {
            get {
                return ResourceManager.GetString("route_vehicle_arrives_st_format", resourceCulture);
            }
        }
        
        public static string route_vehicle_arrives_arrives_format {
            get {
                return ResourceManager.GetString("route_vehicle_arrives_arrives_format", resourceCulture);
            }
        }
        
        public static string no_vehicle_forecast {
            get {
                return ResourceManager.GetString("no_vehicle_forecast", resourceCulture);
            }
        }
        
        public static string route_vehicles_no_data {
            get {
                return ResourceManager.GetString("route_vehicles_no_data", resourceCulture);
            }
        }
        
        public static string vehicle_forecast_no_data {
            get {
                return ResourceManager.GetString("vehicle_forecast_no_data", resourceCulture);
            }
        }
        
        public static string route_stop_forecast_no_data {
            get {
                return ResourceManager.GetString("route_stop_forecast_no_data", resourceCulture);
            }
        }
        
        public static string route_stops_view_search_hint {
            get {
                return ResourceManager.GetString("route_stops_view_search_hint", resourceCulture);
            }
        }
        
        public static string meters_short {
            get {
                return ResourceManager.GetString("meters_short", resourceCulture);
            }
        }
        
        public static string kilometers_short {
            get {
                return ResourceManager.GetString("kilometers_short", resourceCulture);
            }
        }
        
        public static string locating_countdown_format {
            get {
                return ResourceManager.GetString("locating_countdown_format", resourceCulture);
            }
        }
        
        public static string animate_markers_label {
            get {
                return ResourceManager.GetString("animate_markers_label", resourceCulture);
            }
        }
        
        public static string select_location_btn {
            get {
                return ResourceManager.GetString("select_location_btn", resourceCulture);
            }
        }
        
        public static string show_vehicle_on_map_confirm_format {
            get {
                return ResourceManager.GetString("show_vehicle_on_map_confirm_format", resourceCulture);
            }
        }
        
        public static string about_design_text {
            get {
                return ResourceManager.GetString("about_design_text", resourceCulture);
            }
        }
        
        public static string vasiliy_moskaev {
            get {
                return ResourceManager.GetString("vasiliy_moskaev", resourceCulture);
            }
        }
        
        public static string andrey_ivanov {
            get {
                return ResourceManager.GetString("andrey_ivanov", resourceCulture);
            }
        }
        
        public static string dmitriy_kataskin {
            get {
                return ResourceManager.GetString("dmitriy_kataskin", resourceCulture);
            }
        }
        
        public static string about_programming_text {
            get {
                return ResourceManager.GetString("about_programming_text", resourceCulture);
            }
        }
        
        public static string about_licenses_text {
            get {
                return ResourceManager.GetString("about_licenses_text", resourceCulture);
            }
        }
        
        public static string about_image_licenses_text {
            get {
                return ResourceManager.GetString("about_image_licenses_text", resourceCulture);
            }
        }
        
        public static string city_saransk_name {
            get {
                return ResourceManager.GetString("city_saransk_name", resourceCulture);
            }
        }
        
        public static string city_barnaul_name {
            get {
                return ResourceManager.GetString("city_barnaul_name", resourceCulture);
            }
        }
        
        public static string city_ryazan_name {
            get {
                return ResourceManager.GetString("city_ryazan_name", resourceCulture);
            }
        }
        
        public static string city_kursk_name {
            get {
                return ResourceManager.GetString("city_kursk_name", resourceCulture);
            }
        }
        
        public static string city_cheboksary_name {
            get {
                return ResourceManager.GetString("city_cheboksary_name", resourceCulture);
            }
        }
        
        public static string city_tambov_name {
            get {
                return ResourceManager.GetString("city_tambov_name", resourceCulture);
            }
        }
        
        public static string city_oryol_name {
            get {
                return ResourceManager.GetString("city_oryol_name", resourceCulture);
            }
        }
        
        public static string city_novgorod_name {
            get {
                return ResourceManager.GetString("city_novgorod_name", resourceCulture);
            }
        }
        
        public static string ilya_elohoff {
            get {
                return ResourceManager.GetString("ilya.elohoff", resourceCulture);
            }
        }
        
        public static string dmitry_fominykh {
            get {
                return ResourceManager.GetString("dmitry.fominykh", resourceCulture);
            }
        }
        
        public static string andrey_ivanovich {
            get {
                return ResourceManager.GetString("andrey.ivanovich", resourceCulture);
            }
        }
    }
}
